### ISSUE TITLE
Mark Windows build as broken?

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/pytango-feedstock#23]
### Comment:

Following up https://gitlab.com/tango-controls/pytango/-/issues/511, shall the windows builds be marked broken?

AFAIU, the latest working build is the one from the wheel, `9.3.1`. Or is there newer working version? The best option probably remains to stick with Python <= 3.8, and use the wheel from `pip install pytango`.

**Comment by ajoubertza** [comment]
I don't think so.

The problem with the Conda Windows packages isn't with PyTango directly, but rather the omniorb Windows package.  So all projects that depend on it (cpptango, tango-test, PyTango, etc.) have the same issue on Windows.

However, PyTango can still be used on Windows for local development.  I.e., if client and device server are using the same Conda packages on Windows.  It isn't completely useless.

We just need to fix the omniorb compilation issue https://github.com/conda-forge/omniorb-feedstock/issues/37 soon.

The Windows binary wheels on PyPI are OK.  From today PyTango version 9.4.1 is available, but only with Python versions 3.6, 3.7 and 3.8.
